version: '{build}'
skip_tags: true
image: Visual Studio 2017
configuration: Release
platform: Any CPU
clone_depth: 1
before_build:
 - cmd: '"src/.nuget/NuGet.exe" restore src/Simplify.sln'
build:
  publish_nuget: true
  parallel: true
  verbosity: minimal
test_script:
 - ps: .\RunTests.ps1
deploy_script:
 - ps: .\MakeSourcePackages.ps1
